src/drivers/eventSink.js, src/ui/App.js, src/ui/bootstrap.js, src/ui/pwd/index.template.hbs, src/ui/search/index.js
the keyboard on mobile must hide once the search is completed
fixes #30
=> fix(ui): auto hide textbox on successful music search

src/ui/controls/PlaybackButtons.js
=> fix(component): Showing feedback if playing if song is failed

.eslintrc, .travis.yml, package.json, src/Utils/SoundCloud.js, src/Utils/isTrackPlaying.js, src/drivers/audio.js, src/drivers/router.js, src/ui/App.js, src/ui/controls/Playback.js, src/ui/controls/PlaybackInfo.js, src/ui/playlist/Artwork.js, src/ui/playlist/index.js, src/ui/pwd/sw.js
by default we extend standard config
=> chore(lint): add lint command

src/drivers/documentTitle.js, src/ui/App.js, src/ui/bootstrap.js
this helps users learn about the song that is currently being played
=> feat(ui): display track title in browser title

src/ui/App.js, src/ui/search/index.js
=> fix(search): show loading icon at the time of searching

src/Utils/StyleUtils.js, src/ui/App.js, src/ui/controls/index.js, src/ui/playlist/index.js
position relative causes re-paints when ever the content of the playlist changes
=> Repaint issue on controls

src/ui/App.js, src/ui/playlist/index.js
re-tapping on an item in the playlist will keep toggleling the state between play and pause
fixes #39
=> feat(playlist): create toggleable playback via playlist

src/Utils/Themes.js, src/ui/controls/PlaybackButtons.js, src/ui/controls/PlaybackInfo.js, src/ui/playlist/ArtworkOverlay.js, src/ui/playlist/PlayListItem.js, src/ui/playlist/TrackDetail.js, src/ui/playlist/index.js, src/ui/search/index.js
extra padding existed between artwork and track detail
=> fix(TrackDetail): remove padding

src/components/Main.js
paths are case-sensitive on linux machines
=> fix(main): fix import paths

package.json, src/bootstrapDOM.js, src/components/Main.js, src/components/Models.js, src/components/Playlist.js, src/utils/Actions.js, src/utils/Noop.js, src/utils/Proxy.js, webpack.config.js
=> refactor(Playlist): migrate to stanga

src/utils/OverlayStatus.js, test/test.OverlayStatus.js
initial status should keep getting fired until an audio event is fired
=> fix(playlist): fix playlist not being refreshed

package.json
=> chore(package): update ava to version 0.16.0

webpack.config.js
https://travis-ci.org/funag/ui-core#L385
=> chore(webpack): setup env in webpack config also

src/components/scrobber/scrobber.js, src/components/scrobber/scrobber.style.js, src/lib/Themes.js
touch events were getting miss fired because the area was too small
=> fix(scrobber): increase scrobber touch area

src/components/search-icon/search-icon.js, src/components/search/search.js
search looks bigger when compared to the controls
=> fix(search-icon): use standard block-height from theme for height

src/components/PlaybackButtons.js, src/components/artwork/artwork.js, src/components/html/html.js, src/components/search-icon/search-icon.js, src/lib/StyleUtils.js
remove font-awesome and use material icons instead
=> fix(icons): migrate to material icons

.eslintrc, src/components/PlaybackButtons.js, src/components/artwork/artwork.js, src/components/main/main.js, src/components/playlist-item/playlist-item.js, src/components/playlist/playlist.js, src/components/search-icon/search-icon.js, src/lib/uuid.js
search was listening to global click events
=> fix(search): use isolate for buttons

src/components/artwork/artwork.js, src/components/artwork/artwork.style.js, src/components/controls/controls.js, src/components/controls/controls.style.js, src/components/html/html.style.js, src/components/loader/loader.style.js, src/components/main/main.style.js, src/components/placeholders/placeholders.style.js, src/components/playlist-item/playlist-item.style.js, src/components/playlist/playlist.style.js, src/components/search/search.style.js, src/components/search/search.view.js, src/components/track-details/track-details.style.js, src/components/track-duration/track-duration.style.js, src/lib/JSSHelpers.js
conflicts should be managed manually for now. this enables us to exploit classes across the
applicaiton
=> refactor(JSSHelpers): use a single stylesheet

package.json
=> Revert "Update hyperscript to version 2.0.0 🚀"

src/web-components/mini-audio-control/mini-audio-control.js, src/web-components/mini-audio-control/mini-audio-control.utils.js
loader was being created inside the fg-button element
=> fix(mini-audio-control): fix loader styles

package.json
=> chore(package): update rwc to version 3.0.0

src/sw.js
not doing bails out lighthouse
=> refactor(sw): use "/" instead of "/index.html"
